### ISSUE TITLE
Loss is NaN

### ISSUE THREAD

**Issue by Naive-Bayes** [ligang-cs/CSP-Pedestrain-detection#2]
Great work！It is easy to understand and modify codes.
But when i try to train CSP（resnet50 as backbone）， I met a Problem：Loss is NaN. Even i low lr, it also happen.
 So,I want to ask for some suggestions for this problem

**Comment by ligang-cs** [comment]
Would you please provide more training details? How many gpus  do you use? I suggest only using two GPUs , as more GPUs and larger batchsize may result in unstable training.

**Comment by Naive-Bayes** [comment]
Yes,I find more GPUs and larger batch_size can cause this problem.I use four GTX Titans X,load four imgs per GPU.When training the network,I turn off apex,and set lr = 1e-4.However,this problem disappear when I use two GTX Titans X and two imgs per GPU.
